defmodule THOU.PrettyPrint do
  @moduledoc """
  Contains functionality to pretty-print results generated by the prover, which
  includes an assignment of truth values to literals, generated unification
  constraints and the final result of the prover.
  """

  import BeHOLd.ClassicalHOL.Patterns, only: [negated: 1]

  @doc """
  Converts a given assignment to literals as `MapSet` containing negated or
  non-negated terms, depending on their truth value, to a pretty-printed string
  representation.
  """
  @spec pp_assignment(MapSet.t(HOL.Data.hol_term())) :: String.t()
  def pp_assignment(clause) when is_struct(clause, MapSet) do
    pretty_assignments =
      Enum.map(clause, fn t ->
        case t do
          negated(inner) -> "#{PrettyPrint.pp_term(inner, false)} ← false"
          _ -> "#{PrettyPrint.pp_term(t, false)} ← true"
        end
      end)

    "[" <> Enum.join(pretty_assignments, ", ") <> "]"
  end

  @doc """
  Converts a given list of constraints to a pretty-printed string
  representation. A constraint is a tuple of terms which describes an equality
  relation between both.
  """
  @spec pp_constraints([{HOL.Data.hol_term(), HOL.Data.hol_term()}]) :: String.t()
  def pp_constraints(constraints) when is_list(constraints) do
    pretty_constraints =
      Enum.map(constraints, fn {t1, t2} ->
        "#{PrettyPrint.pp_term(t1, false)} = #{PrettyPrint.pp_term(t2, false)}"
      end)

    "[" <> Enum.join(pretty_constraints, ", ") <> "]"
  end

  @doc """
  Converts the result of the `THOU.Prover.prove/4` function to a pretty-printed
  string representation.
  """
  @spec pp_proof_result(THOU.Prover.proof_result()) :: String.t()
  def pp_proof_result(res) do
    case res do
      {:valid, :proven} ->
        "STATUS: Theorem (Proof Found)"

      {:countersat, countermodel} ->
        "STATUS: CounterSatisfiable (Counter-model found)\n#{countermodel}"

      {:unknown, nil, reason} ->
        "STATUS: Unknown (#{reason})"

      {:unknown, partial_model, reason} ->
        "STATUS: Unknown (#{reason})\nPartial Model: #{partial_model}"
    end
  end
end
