defmodule THOU.Tableaux do
  @moduledoc """
  Defines a function `tableau/3` for tree-like model search for a given set of
  formulas with the intention of prooving a formula by showing that its
  negation is unsatisfiable.

  For every possible state, a tableau rule is defined which can be applied. The
  search is done if tableau closed form is reached, i.e., no further rules can
  be applied and the formulas are unsatisfiable. If branches stay open, the
  formulas might be satisfiable.

  In general, there are branching rules like for disjunction and non-branching
  rules like for conjunction. This creates an and-or-tree where the
  and-branches are given by the branching rules (all must be closed) and the
  or-branches are given by the possible unifiers which can close a branch.

  Note that the extensionality axiom currently is not implemented in the
  procedure. While simple cases like `p(a & b) => p(b & a)` are solvable via
  rewriting through the simple orientation of connectives happening in
  `THOU.Preprocessing.Rewriting`, a problem like `p(a) & p(b) => p(a & b)` is
  still not provable.
  """

  use THOU.Tableaux.RuleMacros
  import HOL.Data
  import HOL.Terms
  import HOL.Unification
  import BeHOLd.ClassicalHOL.{Definitions, Patterns}
  import BeHOLd.Util.TypeInference, only: [unknown_type?: 1]
  import THOU.Util
  import THOU.PrettyPrint
  alias THOU.Preprocessing.Rewriting
  alias THOU.Heuristics.NCPO
  alias THOU.Data.Parameters
  require Logger
  require Record

  @doc group: :Internals
  @doc """
  This function creates a new state for the tableau. It should not be called
  under normal usage of the prover as it is just an internal data
  representation.
  """
  Record.defrecord(:tableau_state,
    clause: MapSet.new(),
    constraints: [],
    incomplete?: false,
    inst_count: %{}
  )

  @doc """
  This function creates an unification checkpoint for the tableau. It should
  not be called under normal usage of the prover as it is just an internal data
  representation.
  """
  Record.defrecord(:unif_checkpoint, substs: nil, constrs: nil)

  @typedoc """
  Definitions, e.g. those generated by the BeHOLd library, are represented as a
  map mapping a symbol's name to an equation where the right-hand side
  describes the definition of the symbol.
  """
  @type definitions() :: %{String.t() => HOL.Data.hol_term()}

  @typedoc """
  Unification constraints are represented as term pair where it is asserted
  that both terms must remain unifiable when searching for new unifiers.
  """
  @type constraints() :: [{HOL.Data.hol_term(), HOL.Data.hol_term()}]

  @typedoc """
  Each tableau needs to keep track of the current clause (atoms encountered on
  the path so far), the collected constraints from branch closure, whether the
  instantiation of a quantifier exceeded the instantiation limit and a map to
  keep track of the previous instantiations.
  """
  @type tableau_state() ::
          record(
            :tableau_state,
            clause: MapSet.t(),
            constraints: constraints(),
            incomplete?: boolean(),
            inst_count: %{HOL.Data.hol_term() => pos_integer()}
          )

  @typep unif_checkpoint() ::
           record(:unif_checkpoint,
             substs: [HOL.Data.substitution()],
             constrs: [HOL.Data.Unification.term_pair()]
           )

  @typedoc """
  The tableau have one of three possible outcomes, which are tuples containing
  the state of the result and the respective data associated with that state.
  For `:closed` this means the final unification checkpoints, all leading to
  branch closure. For both `:open` and `:incomplete` cases, these are a model
  and constraints under which this model is true. For the `:incomplete` case,
  this model is partial, as the formula might as well be true.
  """
  @type tableau_res() ::
          {:closed, [unif_checkpoint()]}
          | {:open, MapSet.t(HOL.Data.hol_term()), [HOL.Data.hol_term()]}
          | {:incomplete, MapSet.t(HOL.Data.hol_term()), [HOL.Data.hol_term()]}

  @initial_state {:tableau_state, MapSet.new(), [], false, %{}}

  @doc """
  This function is the heart of the prover. It describes a tree-like search for
  a contradiction. Every possible state is a tableau for which a specific rule
  is defined. One of the possible `tableau_res` is returned.

  Parameters that can be given to the function are whether simplify the formula
  on propositional level based on e-graphs, just orient conjunctions and
  disjunctions or don't preprocess the formula, the branch heuristic to use,
  the maximum number of instantiations of quantifiers, the unification depth
  and the maximum number of workers to use when checking unification
  checkpoints in parallel. Parameters are specified in `THOU.Data.Parameters`.
  """
  @spec tableau([HOL.Data.hol_term()], definitions(), Parameters.t(), tableau_state()) ::
          tableau_res()
  def tableau(formulas, definitions, parameters, state \\ @initial_state)

  def tableau([], _, _, state) do
    tableau_state(incomplete?: incomplete?, clause: clause, constraints: constraints) = state

    if incomplete? do
      # empty formulas and incomplete flag -> rules exhausted while max_inst met
      Logger.notice("OPEN: no formulas remain, exceeded maximum instantiation limit")
      {:incomplete, clause, constraints}
    else
      Logger.notice("OPEN: no formulas remain")
      {:open, clause, constraints}
    end
  end

  def tableau([current_formula | rest], definitions, parameters, state) do
    tableau_state(clause: clause) = state

    "Processing formula #{PrettyPrint.pp_term(current_formula)}" |> Logger.notice()

    formula = preprocess(current_formula, parameters)

    rest_pp = Enum.map(rest, &PrettyPrint.pp_term/1) |> inspect()
    ("Rest: " <> rest_pp) |> Logger.info()
    clause_pp = Enum.map(clause, &PrettyPrint.pp_term/1) |> inspect()
    ("Clause: " <> clause_pp) |> Logger.info()

    apply_rule(formula, rest, definitions, parameters, state)
  end

  #############################################################################
  # TAUTOLOGIES
  #############################################################################

  deftautology("⊤", true_term())
  deftautology("¬⊥", negated(false_term()))
  deftautology("=r", equality(a, a))

  #############################################################################
  # CONTRADICTIONS
  #############################################################################

  defcontradiction("⊥", false_term())
  defcontradiction("¬⊤", negated(true_term()))
  defcontradiction("¬=r", equality(a, a))

  #############################################################################
  # ALPHA RULES (LINEAR)
  #############################################################################

  defalpha("¬¬", negated(negated(a)), do: [a])
  defalpha("∧", conjunction(a, b), do: [a, b])
  defalpha("¬∨", negated(disjunction(a, b)), do: [negate(a), negate(b)])
  defalpha("¬⊃", negated(implication(a, b)), do: [a, negate(b)])

  #############################################################################
  # BETA RULES (BRANCHING)
  #############################################################################

  defbeta("∨", disjunction(a, b), do: {a, b})
  defbeta("¬∧", negated(conjunction(a, b)), do: {negate(a), negate(b)})
  defbeta("⊃", implication(a, b), do: {negate(a), b})
  defbeta("≡", equivalence(a, b), do: {[a, b], [negate(a), negate(b)]})
  defbeta("¬≡", negated(equivalence(a, b)), do: {[negate(a), b], [a, negate(b)]})

  #############################################################################
  # GAMMA RULES (UNIVERSAL)
  #############################################################################

  defgamma "Π", universal_quantification(body), body do
    mk_appl_term(body, fresh_term)
  end

  defgamma "¬Σ", negated(existential_quantification(body)), body do
    negate(mk_appl_term(body, fresh_term))
  end

  #############################################################################
  # DELTA RULES (EXISTENTIAL)
  #############################################################################

  defdelta "Σ", existential_quantification(body), body do
    mk_appl_term(body, skolem_term)
  end

  defdelta "¬Π", negated(universal_quantification(body)), body do
    negate(mk_appl_term(body, skolem_term))
  end

  #############################################################################
  # EQUALITY RULES
  #############################################################################

  defalpha "=o", typed_equality(a, b, type_o()) do
    [equivalent_term() |> mk_appl_term(a) |> mk_appl_term(b)]
  end

  defalpha "¬=o", negated(typed_equality(a, b, type_o())) do
    eq = equivalent_term() |> mk_appl_term(a) |> mk_appl_term(b)
    [neg_term() |> mk_appl_term(eq)]
  end

  defmaybeatomic "=ι", typed_equality(a, b, type(args: []) = t), t, :pos do
    [mk_leibnitz_equality(a, b)]
  end

  defmaybeatomic "¬=ι", negated(typed_equality(a, b, type(args: []) = t)), t, :neg do
    [negate(mk_leibnitz_equality(a, b))]
  end

  defalpha "=α⇾β", equality(a, b) do
    [mk_ext_equality(a, b)]
  end

  defalpha "¬=α⇾β", negated(equality(a, b)) do
    [negated(mk_ext_equality(a, b))]
  end

  #############################################################################
  # DEFINITIONS
  #############################################################################

  defunfold "definition", hol_term(head: declaration(kind: :co, name: name), args: args) do
    unfolded
  end

  defunfold "negated definition",
            negated(hol_term(head: declaration(kind: :co, name: name), args: args)) do
    negate(unfolded)
  end

  #############################################################################
  # ATOM RULES
  #############################################################################

  defatomic(negated(_), :neg)

  defatomic(_, :pos)

  #############################################################################
  # HELPER FUNCTIONS
  #############################################################################

  @spec preprocess(HOL.Data.hol_term(), Parameters.t()) :: HOL.Data.hol_term()
  defp preprocess(formula, parameters) do
    case parameters.rewrite do
      :simplify ->
        f = Rewriting.simplify(formula)
        "Simplified: #{PrettyPrint.pp_term(f)}" |> Logger.notice()
        f

      :orient ->
        f = Rewriting.orient(formula)
        "Oriented: #{PrettyPrint.pp_term(f)}" |> Logger.notice()
        f

      _ ->
        formula
    end
  end

  @spec handle_atom(
          HOL.Data.hol_term(),
          :pos | :neg,
          [HOL.Data.hol_term()],
          definitions(),
          Parameters.t(),
          tableau_state()
        ) ::
          tableau_res()
  defp handle_atom(formula, polarity, rest, definitions, parameters, state) do
    tableau_state(clause: clause, constraints: constraints) = state

    unif_set =
      case polarity do
        :pos -> lit_negate(clause)
        :neg -> clause
      end

    stripped_formula =
      case formula do
        hol_term(bvars: [], head: neg_const(), args: [inner]) -> inner
        _ -> formula
      end

    unif_checkpoints = unify_with_literals(stripped_formula, unif_set, constraints, parameters)

    case unif_checkpoints do
      [] ->
        # no solutions found with current atom
        tableau(
          rest,
          definitions,
          parameters,
          tableau_state(state, clause: MapSet.put(clause, formula))
        )

      candidates ->
        {:closed, candidates}
    end
  end

  @spec branch(
          HOL.Data.hol_term() | [HOL.Data.hol_term()],
          HOL.Data.hol_term() | [HOL.Data.hol_term()],
          [HOL.Data.hol_term()],
          definitions(),
          Parameters.t(),
          tableau_state()
        ) :: tableau_res()
  defp branch(a, b, rest, definitions, parameters, state) do
    {first_branch, second_branch} = order_branches(a, b, parameters)

    case tableau(first_branch ++ rest, definitions, parameters, state) do
      {:closed, unif_checkpoints} ->
        process_second_branch(
          unif_checkpoints,
          second_branch,
          rest,
          definitions,
          parameters,
          state
        )

      other_result ->
        other_result
    end
  end

  defp order_branches(a, b, parameters) do
    a_terms = List.flatten([a])
    b_terms = List.flatten([b])

    if parameters.branch_heuristic == :ncpo and NCPO.smaller_multiset?(b_terms, a_terms) do
      {b_terms, a_terms}
    else
      {a_terms, b_terms}
    end
  end

  defp process_second_branch([], _branch, _rest, _defs, _params, _state) do
    {:closed, []}
  end

  defp process_second_branch(solutions, branch, rest, defs, params, state) do
    task_function = fn checkpoint ->
      solve_continuation(checkpoint, branch, rest, defs, params, state)
    end

    results =
      if params.max_concurrency > 1 do
        solutions
        |> Task.async_stream(task_function,
          max_concurrency: params.max_concurrency,
          ordered: false,
          timeout: :infinity
        )
        |> Enum.map(fn {:ok, res} -> res end)
      else
        Enum.map(solutions, task_function)
      end

    aggregate_branch_results(results)
  end

  defp solve_continuation(checkpoint, branch, rest, defs, params, state) do
    unif_checkpoint(substs: sigma, constrs: constraints) = checkpoint
    tableau_state(clause: gamma) = state

    new_branch = apply_subst(sigma, branch)
    new_rest = apply_subst(sigma, rest)
    new_gamma = apply_subst(sigma, gamma)

    result =
      tableau(
        new_branch ++ new_rest,
        defs,
        params,
        tableau_state(state, clause: new_gamma, constraints: constraints)
      )

    {checkpoint, result}
  end

  defp aggregate_branch_results(results) do
    results
    |> Enum.reduce_while({:open, MapSet.new(), []}, fn {original_cp, res}, _acc ->
      case res do
        {:closed, new_checkpoints} ->
          combined_checkpoints = merge_checkpoints(original_cp, new_checkpoints)
          {:halt, {:closed, combined_checkpoints}}

        {:incomplete, clause, constrs} ->
          {:cont, {:incomplete, clause, constrs}}

        {:open, clause, constrs} ->
          {:cont, {:open, clause, constrs}}
      end
    end)
  end

  defp merge_checkpoints(original_cp, new_checkpoints) do
    unif_checkpoint(substs: old_substs) = original_cp

    if Enum.empty?(new_checkpoints) do
      [original_cp]
    else
      Enum.map(new_checkpoints, fn unif_checkpoint(substs: new_substs) = c ->
        unif_checkpoint(c, substs: apply_subst(new_substs, old_substs) ++ new_substs)
      end)
    end
  end

  @spec unify_with_literals(
          HOL.Data.hol_term(),
          [HOL.Data.hol_term()],
          constraints(),
          Parameters.t()
        ) :: [unif_checkpoint()]
  defp unify_with_literals(formula, literals, constraints, parameters) do
    Enum.reduce(literals, [], fn lit, solutions ->
      ("Trying to unify #{PrettyPrint.pp_term(formula)} with literal #{PrettyPrint.pp_term(lit)}" <>
         " under constraints #{pp_constraints(constraints)}")
      |> Logger.notice()

      result = unify([{formula, lit} | constraints], true, parameters.unification_depth)

      PrettyPrint.pp_res(result) |> Logger.notice()

      {:unif_res_sum, unif_solutions, _} = result

      new_solutions =
        Enum.map(unif_solutions, fn {:unif_sol, substitutions, flexlist} ->
          {:unif_checkpoint, substitutions, flexlist}
        end)

      solutions ++ new_solutions
    end)
  end
end
